sudo: required
dist: trusty
language: python
python:
- '2.6'
- '2.7'
- '3.3'
- '3.4'
- '3.5'
install:
- sudo apt-get update
- sudo apt-get -qq install python-setuptools liblo7
- pip install --upgrade pip
- sudo pip install Cython
- pip install -r requirements.txt
- pip install coverage
- pip install codacy-coverage
- pip install https://github.com/Syntaf/travis-sphinx/archive/master.zip
script:
- cd tests
- coverage run --omit ../pylekture/_version.py --include=../pylekture/"*" test_.py
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then coverage xml; fi
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then coverage report -m; fi
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then python-codacy-coverage -r coverage.xml; fi
- cd ../
- travis-sphinx build
after_success:
- travis-sphinx deploy
- cd tests
- coveralls
