sudo: required
dist: trusty
language: python
python:
  - "2.7"
  - "3.5"
install:
  - sudo apt-get update
  - sudo apt-get -qq install python-setuptools liblo-dev liblo-tools
  - pip install -r requirements.txt
  - pip install travis-sphinx
script:
  - coverage run tests/tests.py
  - coverage report -m
  - travis-sphinx build
after_success: 
  - coveralls
  - travis-sphinx deploy