sudo: required
dist: xenial
language: python
python:
- "2.6"
- "2.7"
- "3.3"
- "3.4"
- "3.5"
- "3.5-dev"
- "3.6"
- "3.6-dev"
- "3.7-dev"
- "3.8-dev"
- "nightly"
install:
- sudo apt-get update
- sudo apt-get -qq install python-setuptools python-dev
- pip install --upgrade pip
- pip install -ve .
- pip install coverage
- pip install codacy-coverage
- pip install https://github.com/Syntaf/travis-sphinx/archive/master.zip
- pip install https://github.com/PixelStereo/pybush/archive/master.zip
script:
- cd tests
- coverage run --omit ../pylekture/_version.py --include=../pylekture/"*" test_.py
- if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then coverage xml; fi
- if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then coverage report -m; fi
- if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then python-codacy-coverage -r coverage.xml; fi
- cd ../
- travis-sphinx build --source docs/source
after_success:
- if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then travis-sphinx deploy; fi
- cd tests
- if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then coveralls; fi
- cd ../
- if [ -n "$TRAVIS_TAG" ]; then twine upload -u ${PyPiUser} -p ${PyPiWord} dist/pylekture*.whl; fi
deploy:
  - provider: releases
    api_key:
      secure: ${GH_TOKEN}
    file_glob: true
    file: dist/pyossia-*.whl
    skip_cleanup: true
    draft: false
    prerelease: true
    on:
      repo: PixelStereo/pylekture
      tags: true
