sudo: required
dist: trusty
language: python
python:
  - "2.7"
install:
  - sudo apt-get update
  - sudo apt-get -qq install python-setuptools liblo-dev liblo-tools
  - pip install requirements.txt
script:
  - coverage run tests/tests.py
  - coverage report
after_success: coveralls
