sudo: required
dist: trusty
language: python
python:
  - "2.7"
install:
  - sudo apt-get install ruby
  - yes '' | ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/linuxbrew/go/install)"
  - sudo apt-get install -y build-essential
  - export PATH="$HOME/.linuxbrew/bin:$PATH"
  - export MANPATH="$HOME/.linuxbrew/share/man:$MANPATH"
  - export INFOPATH="$HOME/.linuxbrew/share/info:$INFOPATH"
  - brew install liblo
  - sudo pip install Cython
  - pip install pyliblo
  - pip install pjlink
script: tests/tests.py
