sudo: required
dist: trusty
language: python
python:
  - "2.7"
  - "3.5"
install:
  - sudo apt-get update
  - sudo apt-get -qq install python-setuptools liblo-dev liblo-tools
  - pip install https://github.com/PixelStereo/pydular/archive/master.zip
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
  - pip install https://github.com/Syntaf/travis-sphinx/archive/master.zip
script:
  - cd tests
  - coverage run tests.py
  - coverage report -m
  - cd ../
  - travis-sphinx build
after_success: 
  - coveralls
  - travis-sphinx deploy