sudo: required
dist: trusty
language: python
python:
  - "2.7"
  - "3.5"
install:
  - sudo apt-get --fix-missing update
  - sudo apt-get -qq install python-setuptools liblo-dev liblo-tools
  - pip install https://github.com/PixelStereo/pydular/archive/master.zip
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
  - pip install travis-sphinx
script:
  - cd tests
  - coverage run tests.py
  - coverage report -m
  - cd ../
  - travis-sphinx build
after_success: 
  - coveralls
  - travis-sphinx deploy
deploy:
  - provider: script
    script: scripts/tag.sh
    skip_cleanup: true
    on:
      tags: true
  - provider: pypi
    user: $PYPIUSER
    password: $PYPIPASSWORD
    skip_cleanup: true
    on:
      tags: true
