sudo: required
dist: trusty
language: python
python:
  - "2.7"
install:
  - sudo apt-get update
  - sudo apt-get -y install python-setuptools
  - sudo apt-get -y install liblo-dev
  - sudo apt-get -y install liblo-tools #python-liblo
  - pip install pyliblo
  - pip install pjlink
  - pip install coveralls
script:
  - coverage run tests/tests.py
  - coverage report
after_success: coveralls