sudo: required
dist: trusty
language: python
python:
  - "2.7"
install:
  - sudo apt-get update
  - sudo apt-get -y install liblo-tools
  - sudo pip install Cython
  - pip install pyliblo
  - pip install pjlink
script: tests/tests.py
